### ISSUE TITLE
What's the FPS?

### ISSUE THREAD

**Issue by Phanthomphax** [MegaApuTurkUltra/ScratchTools#1]
I don't know what to do in FPS thingy, and I do not get anything to adjust that. This is it: https://scratch.mit.edu/projects/64975384/ and I try exactly to make it fit but it's little bit different sometime. Can you please tell me what is the FPS? Or can you remove Frames per second thingy? It seems that it's just to mess up.

**Comment by MegaApuTurkUltra** [comment]
In the generator, check the checkbox to use 20fps if you're ok with huge amounts of generated data. Otherwise uncheck it to use 10fps. Maybe I should make the generator fill in the fps setting automatically,
